Done HomeWork_Lesson1
Anastazia17/Geekshop pull request #1
Opened 2021-02-22 13:16 UTC by Anastazia17

Change HomeWork_Lesson1

2021-02-22 19:05 UTC, Vokler requested changes

2021-02-22 19:05 UTC, Vokler commented on mainapp/views.py
> +    return render(request, 'mainapp/contact.html')
У вас в mainapp/templates нет шаблона contact.html. Скорее всего из-за этого проблемы

2021-02-22 19:05 UTC, Vokler commented on geekshop/urls.py
> +from mainapp.views import contact
Тут необязательно кадый контроллер вызывать на отдельно строке. Вы можете просто использовать
`from mainapp.views import index, products, contact`

2021-02-25 10:39 UTC, Anastazia17 commented on mainapp/views.py
> +    return render(request, 'mainapp/contact.html')
Исправила.

2021-02-25 10:46 UTC, Anastazia17 commented on geekshop/urls.py
> +from mainapp.views import contact
Исправила.

2021-02-25 15:22 UTC, merged