HomeWork of Lesson 2
Anastazia17/Geekshop pull request #2
Opened 2021-02-25 16:34 UTC by Anastazia17

Done HomeWork of Lesson2

2021-02-26 15:22 UTC, Vokler requested changes

2021-02-26 15:22 UTC, Vokler commented on mainapp/views.py
> +    context = {'title': 'GeekShop - Каталог'}
Было бы отлично добавить сюда в context еще список с products, чтобы в products.html убрать повторяющиеся блоки с отображение продуктов. То есть просто заитерировать products из сщтеуче

2021-02-26 15:23 UTC, Vokler commented
У вас так же конфликты в вашей ветке Lesson_2.
Чтобы их решить, нужно в ветке Lesson_2 сделать git pull master и запушить то, что подтянули из master ветки.
Из-за того, что конфликты, невозможно смержить

2021-03-02 17:18 UTC, Anastazia17 commented on mainapp/views.py
> +    context = {'title': 'GeekShop - Каталог'}
Не понимаю, что имелось ввиду. Оставила всё как есть. Не нашла повторений в коде в файле products.html

2021-03-02 17:24 UTC, Anastazia17 commented on mainapp/views.py
> +    context = {'title': 'GeekShop - Каталог'}
По конфликту в ветке Lesson_2 вроде бы починила. Прошу перепроверить.

2021-03-03 16:21 UTC, Vokler approved these changes

2021-03-03 16:21 UTC, merged