HomeWork of Lesson 3
Anastazia17/Geekshop pull request #3
Opened 2021-03-03 20:32 UTC by Anastazia17

Done HomeWork of Lesson 3

2021-03-04 09:11 UTC, Vokler commented
Вы сказали, что перестал сайт работать после создания админки - а какая ошибка?
Приложите описание ошибки или скрин

2021-03-09 16:34 UTC, Anastazia17 commented
Вот что происходит при подключении к серверу в PyCharm: https://prnt.sc/10h9iq9
А вот что появляется при попытке войти на сайт: https://prnt.sc/10h9jdq

2021-03-09 16:40 UTC, Anastazia17 commented
Вот полный текст в PyCharm:
https://prnt.sc/10h9s3f
https://prnt.sc/10h9t1p
Что могло произойти? И как это починить?

2021-03-11 09:55 UTC, Vokler requested changes

2021-03-11 09:55 UTC, Vokler commented on geekshop/urls.py
>      path('products/', products),
У вас ошибка из-за того, что вы нигде в urls.py не указали `name`, а в шаблоне пытаетесь ссылаться, используя не созданное name
![image](https://user-images.githubusercontent.com/21297042/110769292-10cd5080-8269-11eb-89df-3cb1a9615ceb.png)

2021-03-11 11:43 UTC, Anastazia17 commented on geekshop/urls.py
>      path('products/', products),
А где нужно указать это name? Вроде у Вас тоже нигде нет в urls.py указанного name. У Вас списала так сказать))

2021-03-11 11:51 UTC, Anastazia17 commented on geekshop/urls.py
>      path('products/', products),
Все. Разобралась. Заработало! Спасибо)

2021-03-11 13:56 UTC, merged